import ChatBox from "@/containers/chat-box";
import Head from "next/head";

const index = () => {
  return (
    <>
      <Head>
        <title>Chat </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/Tracker.ico' />
      </Head>
      <ChatBox />
    </>
  );
};
index.getInitialProps = async () => {
  return {
    layoutType: "fullWidth",
  };
};
export default index;

index.requireAuth = true;
