import { Html, Head, Main, NextScript } from "next/document";
import { switzer } from "@/assests/fonts/fonts";

export default function Document() {
  return (
    <Html lang="en" suppressHydrationWarning>
      <Head>
        {/* <title>Zwilt Settings</title> */}
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8"/>  */}
        {/* <meta name="description" content="Zwilt settings" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={switzer.className}>
        <div>
          <Main />
          <NextScript />
        </div>
      </body>
    </Html>
  );
}
